name: Generate Spritesheets

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    generate-spritesheets:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Install python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Generate spritesheets
              run: python spritesheet.py

            - name: Clean working directory
              run: |
                  git rm -rf .
                  git clean -fxd

            - name: Copy spritesheets to repository
              run: |
                  mkdir -p spritesheets
                  cp -r /tmp/spritesheets/* .

            - name: Setup Git LFS
              run: |
                  git lfs install
                  git lfs track "*.png"
                  git add .gitattributes

            - name: Create orphan branch
              run: |
                  git checkout --orphan sprites
                  git reset --hard
                  git commit --allow-empty -m "Initial commit for sprites branch"

            - name: Commit and push changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "Update spritesheets"
                  branch: sprites
                  file_pattern: "*.png"
                  push_options: --force
                  skip_checkout: true
                  create_branch: true
