name: Export GLTF from Blender

on:
    push:
        paths:
            - "**.blend"

    workflow_dispatch:

jobs:
    export_gltf:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  lfs: true

            - name: Pull LFS
              run: |
                  git lfs pull

            - name: Install Blender
              run: |
                  sudo apt update
                  sudo apt install blender -y

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: 3.13

            - name: Install Python dependencies
              run: |
                  pip install -r requirements.txt

            - name: Install Blender dependencies
              run: |
                  blender --background --python-expr "import pip; pip.main(['install', 'requests', 'numpy'])"

            - name: Setup Minio Client
              uses: hostwithquantum/setup-mc@main

            - name: Configure Minio Alias
              run: |
                  mc alias set minio https://s3.minio.kristn.co.uk \
                    ${{ secrets.MINIO_ACCESS_KEY }} \
                    ${{ secrets.MINIO_SECRET_KEY }}

            - name: Run compile script
              run: |
                  python3 compile-gltf.py

            - name: Upload compiled models
              run: |
                  mc cp --recursive ./output/ minio/ratartd-models/
